import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, CircleDollarSign, ExternalLink, ShieldCheck, TriangleAlert } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { saveEligibilityFact, trackFunding } from "./actions";

export default async function FundingPage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect("/login");
 const {data:access}=await supabase.from("user_artist_access").select("artist_id").eq("user_id",user.id).limit(1).maybeSingle();
 const artistId=access?.artist_id;
 const programs=(await supabase.from("funding_programs").select("*").neq("verification_status","archived").order("deadline_date",{ascending:true,nullsFirst:false})).data??[];
 const today=new Date().toISOString().slice(0,10);
 const projects=artistId?(await supabase.from("projects").select("id,name,organization_id").eq("artist_id",artistId).order("name")).data??[]:[];
 const organizations=artistId?(await supabase.from("organizations").select("id,name").eq("artist_id",artistId).order("name")).data??[]:[];
 const factDefinitions=artistId?(await supabase.from("fact_definitions").select("fact_key,subject_type,question,value_type,unit,help_text")).data??[]:[];
 const verificationQueue:any[]=[];
 if(artistId) for(const project of projects){
  const {data:q}=await supabase.rpc("funding_verification_queue",{target_artist:artistId,target_project:project.id});
  for(const row of q??[]) verificationQueue.push({project_id:project.id,project_name:project.name,...row});
 }
 const dedupedVerificationQueue=Array.from(new Map(verificationQueue.map((q:any)=>[q.funding_program_id,q])).values()).sort((a:any,b:any)=>a.priority-b.priority);
 const factDefinitionByKey=new Map(factDefinitions.map(d=>[d.fact_key,d]));
 const organizationById=new Map(organizations.map(o=>[o.id,o]));
 const applications=artistId?(await supabase.from("funding_applications").select("id,status,funding_programs(provider_name,name),projects(name)").eq("artist_id",artistId).order("created_at",{ascending:false})).data??[]:[];
 const v2Rows:any[]=[];
 if(artistId) for(const project of projects){
  const orgId=project.organization_id??null;
  const {data:detail}=await supabase.rpc("evaluate_funding_eligibility_v23",{target_artist:artistId,target_project:project.id,target_organization:orgId});
  const grouped=new Map<string,any>();
  for(const row of detail??[]){const g=grouped.get(row.funding_program_id)??{project_id:project.id,project_name:project.name,funding_program_id:row.funding_program_id,provider_name:row.provider_name,program_name:row.program_name,satisfied_count:0,missing_count:0,not_met_count:0,total_count:0};g.total_count++;if(row.criterion_status==="satisfied")g.satisfied_count++;else if(row.criterion_status==="missing_information"||row.criterion_status==="pending_context")g.missing_count++;else if(row.criterion_status==="criterion_not_met"&&row.blocking&&row.criterion_kind==="eligibility")g.not_met_count++;grouped.set(row.funding_program_id,g);}
  const {data:readiness}=await supabase.rpc("funding_program_readiness",{target_artist:artistId,target_project:project.id});
  const readinessByProgram=new Map((readiness??[]).map((r:any)=>[r.funding_program_id,r]));
  for(const g of grouped.values()){const rd:any=readinessByProgram.get(g.funding_program_id);g.readiness_status=rd?.readiness_status??"to_verify";g.readiness_reason=rd?.reason??"Niveau de vérification inconnu.";g.eligibility_status=g.readiness_status!=="ready"?"verification_required":g.not_met_count?"criterion_not_met":g.missing_count?"missing_information":"potentially_compatible";v2Rows.push(g);}
 }
 const missingFacts:any[]=[];
 if(artistId) for(const project of projects){
  const orgId=project.organization_id??null; const org=orgId?organizationById.get(orgId):null; const {data}=await supabase.rpc("evaluate_funding_eligibility_v23",{target_artist:artistId,target_project:project.id,target_organization:orgId});
  for(const row of (data??[]).filter((x:any)=>(x.criterion_status==="missing_information"||x.criterion_status==="pending_context")&&x.blocking&&x.criterion_kind==="eligibility"&&["project","organization"].includes(x.criterion_subject_type))) missingFacts.push({project_id:project.id,project_name:project.name,organization_id:orgId,organization_name:org?.name,...row});
 }
 const numericOps=new Set(["gte","lte","gt","lt"]);
 const dedupedMissing=Array.from(new Map(missingFacts.map((m:any)=>[(m.criterion_subject_type==="organization"?(m.organization_id||"no-org"):m.project_id)+"|"+m.criterion_key,m])).values()) as any[];
 const missingImpact=new Map<string,number>(); for(const m of missingFacts){const k=(m.criterion_subject_type==="organization"?(m.organization_id||"no-org"):m.project_id)+"|"+m.criterion_key;missingImpact.set(k,(missingImpact.get(k)??0)+1);}
 const rankedMissing=[...dedupedMissing].sort((a:any,b:any)=>{const ka=(a.criterion_subject_type==="organization"?(a.organization_id||"no-org"):a.project_id)+"|"+a.criterion_key;const kb=(b.criterion_subject_type==="organization"?(b.organization_id||"no-org"):b.project_id)+"|"+b.criterion_key;return (missingImpact.get(kb)??0)-(missingImpact.get(ka)??0);});
 const nextQuestion=rankedMissing[0]??null;
 const statusLabels:Record<string,string>={potentially_compatible:"Potentiellement compatible",missing_information:"Informations manquantes",criterion_not_met:"Condition non remplie"};
 return <main className="mx-auto min-h-screen max-w-md bg-white px-5 pb-12 pt-7">
  <Link href="/" className="inline-flex items-center gap-2 text-sm font-medium text-neutral-600"><ArrowLeft size={17}/> Cockpit</Link>
  <div className="mt-6 flex items-center gap-3"><div className="rounded-xl bg-neutral-100 p-3"><CircleDollarSign size={24}/></div><div><p className="text-sm font-semibold text-neutral-500">ArtistPilot</p><h1 className="text-2xl font-bold">Financements</h1></div></div>
  <div className="mt-5 rounded-2xl border border-neutral-200 p-4 text-sm text-neutral-600"><p className="font-semibold text-neutral-900">Principe de sécurité</p><p className="mt-1">ArtistPilot distingue les dispositifs vérifiés de ceux à vérifier. Une aide n’est jamais présentée comme acquise : l’éligibilité sera calculée à partir de faits connus et de sources officielles.</p></div>
  {projects.some(p=>!p.organization_id)&&<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Certains projets n’ont pas encore de structure porteuse. Les critères de structure restent inconnus pour ces projets jusqu’à ce qu’une structure soit associée.</div>}
  <section className="mt-7"><h2 className="font-semibold">Analyse d’éligibilité V2.3</h2>{projects.length===0?<p className="mt-3 rounded-2xl border border-dashed p-4 text-sm text-neutral-600">Ajoute d’abord un projet pour lancer l’analyse.</p>:v2Rows.length===0?<p className="mt-3 rounded-2xl border border-dashed p-4 text-sm text-neutral-600">Aucun critère vérifié applicable pour le moment. ArtistPilot ne déduit rien en l’absence de données.</p>:<div className="mt-3 space-y-2">{v2Rows.map(m=><div key={m.project_id+"-"+m.funding_program_id} className="rounded-2xl border p-4"><p className="text-xs font-semibold uppercase text-neutral-500">{m.provider_name} · {m.project_name}</p><p className="mt-1 font-medium">{m.program_name}</p><p className="mt-1 text-sm font-semibold">{statusLabels[m.eligibility_status]??m.eligibility_status}</p><p className="mt-1 text-xs text-neutral-600">{m.satisfied_count}/{m.total_count} critères satisfaits · {m.missing_count} information(s) manquante(s){m.not_met_count?(" · "+m.not_met_count+" condition(s) non remplie(s)"):""}</p></div>)}</div>}</section>
  <section className="mt-7"><h2 className="font-semibold">Prochaine information utile</h2>{!nextQuestion?<p className="mt-3 rounded-2xl border border-dashed p-4 text-sm text-neutral-600">Aucune information déterministe manquante à demander pour le moment.</p>:(()=>{const m:any=nextQuestion;const def:any=factDefinitionByKey.get(m.criterion_key);const numeric=def?.value_type==="number"||(numericOps.has(m.operator)&&typeof m.expected_value==="number");const key=(m.criterion_subject_type==="organization"?(m.organization_id||"no-org"):m.project_id)+"|"+m.criterion_key;const impact=missingImpact.get(key)??1;return <form action={saveEligibilityFact} className="mt-3 rounded-2xl border border-neutral-300 p-4"><input type="hidden" name="subject_type" value={m.criterion_subject_type}/><input type="hidden" name="subject_id" value={m.criterion_subject_type==="organization"?m.organization_id:m.project_id}/><input type="hidden" name="fact_key" value={m.criterion_key}/><div className="flex items-start justify-between gap-3"><p className="text-xs font-semibold uppercase text-neutral-500">{m.provider_name} · {m.criterion_subject_type==="organization"?(m.organization_name||"Structure"):m.project_name}</p><span className="rounded-full bg-neutral-100 px-2 py-1 text-[11px] font-medium">{impact} aide{impact>1?"s":""} concernée{impact>1?"s":""}</span></div><p className="mt-2 text-sm font-medium">{def?.question||m.source_text||m.criterion_key}</p>{def?.help_text&&<p className="mt-1 text-xs text-neutral-500">{def.help_text}</p>}{numeric?<div className="mt-3 flex gap-2"><input required name="value" type="number" step="any" min="0" placeholder={def?.unit?`Valeur (${def.unit})`:"Valeur"} className="min-w-0 flex-1 rounded-xl border px-3 py-2 text-sm"/><button className="rounded-xl bg-black px-4 py-2 text-sm font-semibold text-white">Enregistrer</button></div>:<div className="mt-3 flex gap-2"><button name="value" value="true" className="flex-1 rounded-xl border px-3 py-2 text-sm font-semibold">Oui</button><button name="value" value="false" className="flex-1 rounded-xl border px-3 py-2 text-sm font-semibold">Non</button></div>}<p className="mt-2 text-xs text-neutral-500">Après ta réponse, ArtistPilot recalcule automatiquement les aides concernées.</p>{m.source_text&&def?.question&&<details className="mt-2 text-xs text-neutral-500"><summary className="cursor-pointer">Voir le critère source</summary><p className="mt-1">{m.source_text}</p>{m.source_url&&<p className="mt-1 break-all">{m.source_url}</p>}</details>}</form>})()}</section>
  <section className="mt-7"><div className="flex items-end justify-between gap-3"><div><h2 className="font-semibold">À revérifier</h2><p className="mt-1 text-xs text-neutral-500">Dispositifs dont les sources ou règles ne permettent pas encore une conclusion forte.</p></div><span className="rounded-full bg-neutral-100 px-2 py-1 text-xs font-semibold">{dedupedVerificationQueue.length}</span></div>{dedupedVerificationQueue.length===0?<p className="mt-3 rounded-2xl border border-dashed p-4 text-sm text-neutral-600">Aucune revérification prioritaire détectée.</p>:<div className="mt-3 space-y-2">{dedupedVerificationQueue.slice(0,5).map((q:any)=><article key={q.funding_program_id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-neutral-500">{q.provider_name}</p><p className="mt-1 text-sm font-semibold">{q.program_name}</p></div><span className="rounded-full bg-amber-50 px-2 py-1 text-[11px] font-medium text-amber-800">Priorité {q.priority}</span></div><p className="mt-2 text-xs text-neutral-600">{q.reason}</p>{q.official_url&&<a href={q.official_url} target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs font-semibold underline">Source officielle</a>}</article>)}</div>}</section>
  <section className="mt-7"><h2 className="font-semibold">Mes dossiers suivis</h2>{applications.length===0?<p className="mt-3 rounded-2xl border border-dashed p-4 text-sm text-neutral-600">Aucun financement suivi pour le moment.</p>:<div className="mt-3 space-y-2">{applications.map(a=>{const fp=a.funding_programs as unknown as {provider_name?:string,name?:string}|null;const pr=a.projects as unknown as {name?:string}|null;return <div key={a.id} className="rounded-2xl border p-4"><p className="font-medium">{fp?.name}</p><p className="text-sm text-neutral-500">{fp?.provider_name}{pr?.name?` · ${pr.name}`:""} · {a.status}</p></div>})}</div>}</section>
  <section className="mt-8"><h2 className="font-semibold">Catalogue</h2>{programs.length===0?<div className="mt-3 rounded-2xl border border-dashed p-5"><p className="font-medium">Catalogue en préparation</p><p className="mt-1 text-sm text-neutral-600">La structure est prête. Aucun dispositif n’est ajouté tant que sa source officielle et son état de vérification ne sont pas enregistrés.</p></div>:<div className="mt-3 space-y-4">{programs.map(p=><article key={p.id} className="rounded-2xl border p-4">
   <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-neutral-500">{p.provider_name}</p><h3 className="mt-1 font-semibold">{p.name}</h3></div>{p.verification_status==="verified"?<ShieldCheck size={20}/>:<TriangleAlert size={20}/>}</div>
   {p.description&&<p className="mt-2 text-sm text-neutral-600">{p.description}</p>}
   <div className="mt-3 flex flex-wrap gap-2 text-xs">{p.deadline_date&&<span className={`rounded-full px-2.5 py-1 ${p.deadline_date<today?"bg-neutral-100 text-neutral-500":"bg-amber-50 text-amber-800"}`}>{p.deadline_date<today?"Dépôt 2026 clos":"Échéance : "+new Intl.DateTimeFormat("fr-FR").format(new Date(p.deadline_date+"T12:00:00"))}</span>}{p.max_amount_eur&&<span className="rounded-full bg-neutral-100 px-2.5 py-1">Jusqu’à {Number(p.max_amount_eur).toLocaleString("fr-FR")} €</span>}</div>
   {p.deadline_text&&<p className="mt-2 text-xs text-neutral-500">{p.deadline_text}</p>}
   <a href={p.official_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-sm font-medium underline">Source officielle <ExternalLink size={14}/></a>
   {(!p.deadline_date||p.deadline_date>=today)&&<form action={trackFunding} className="mt-4 space-y-2"><input type="hidden" name="funding_program_id" value={p.id}/><select name="project_id" defaultValue="" className="h-10 w-full rounded-xl border bg-white px-2 text-sm"><option value="">Projet à définir</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="organization_id" defaultValue="" className="h-10 w-full rounded-xl border bg-white px-2 text-sm"><option value="">Structure à définir</option>{organizations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="h-10 w-full rounded-xl bg-black text-sm font-semibold text-white">Suivre ce financement</button></form>}
  </article>)}</div>}</section>
 </main>
}
