-- Seed only programs verified against official provider pages on 2026-09-21.
insert into public.funding_programs
(provider_name,name,description,official_url,funding_types,project_types,applicant_types,deadline_date,deadline_text,max_amount_eur,eligibility_notes,verification_status,verified_at)
select * from (values
('CNM','Aide à la production phonographique','Soutien aux projets de production phonographique en musiques actuelles, classiques et contemporaine.','https://cnm.fr/aides-financieres/aide-a-la-production-phonographique-3/',ARRAY['production phonographique'],ARRAY['album','ep','single'],ARRAY['personne morale','structure de production phonographique'],'2026-09-30'::date,'Autre dépôt annoncé : 30 octobre 2026',NULL::numeric,'Structure affiliée CNM, personne morale, employeuse des artistes, au moins un an d’existence, détentrice des masters ; autres critères économiques et de projet à vérifier sur la source officielle.','verified',now()),
('CNM','Aide à la production de musique en images','Soutien à la production d’une vidéomusique liée à une actualité phonographique.','https://cnm.fr/aides-financieres/aide-a-la-production-de-musique-en-images/',ARRAY['audiovisuel','clip'],ARRAY['clip'],ARRAY['personne morale','entrepreneur individuel','producteur phonographique','éditeur'],'2026-10-13'::date,NULL,NULL::numeric,'Affiliation CNM ; activité principale d’enregistrement sonore ou d’édition musicale ; employeur des artistes ; prise en charge de la majorité des coûts audiovisuels. Vérifier tous les critères avant dépôt.','verified',now()),
('CNM','Aide à la production et à la diffusion de spectacle vivant','Soutien au producteur générateur pour un projet de production et/ou diffusion de spectacle vivant.','https://cnm.fr/aides-financieres/aide-a-la-production-et-a-la-diffusion-de-spectacle-vivant/',ARRAY['spectacle vivant','diffusion','tournée'],ARRAY['tournee','spectacle'],ARRAY['producteur de spectacle'],'2026-10-07'::date,NULL,NULL::numeric,'Destinée au producteur générateur, employeur du plateau artistique. Affiliation CNM requise ; critères complets à vérifier sur la source officielle.','verified',now()),
('CNM','Crédit d’impôt en faveur de la production phonographique (CIPP)','Crédit d’impôt destiné à soutenir la création, la diversité musicale et la production phonographique.','https://cnm.fr/aides-financieres/credit-dimpot-en-faveur-de-la-production-phonographique/',ARRAY['crédit impôt','production phonographique'],ARRAY['album','ep','single'],ARRAY['entreprise de production phonographique'],'2026-10-19'::date,'Autre date annoncée : 28 décembre 2026 pour le comité du 28 janvier 2027',NULL::numeric,'Dispositif fiscal avec agrément ; l’éligibilité dépend de critères légaux et du projet. Ne pas conclure à l’éligibilité sans vérification complète.','verified',now())
) as v(provider_name,name,description,official_url,funding_types,project_types,applicant_types,deadline_date,deadline_text,max_amount_eur,eligibility_notes,verification_status,verified_at)
where not exists (select 1 from public.funding_programs p where p.official_url=v.official_url);
