-- Add verified/current official programs; preserve closed programs for future-cycle intelligence.
insert into public.funding_programs
(provider_name,name,description,official_url,funding_types,project_types,applicant_types,deadline_date,deadline_text,max_amount_eur,eligibility_notes,verification_status,verified_at)
select * from (values
('SACEM','Aide au livre-disque et autoproduction phonographique Jeune Public','Accompagne les projets phonographiques ou livre-disque à destination du jeune public.','https://aide-aux-projets.sacem.fr/nos-programmes-aide/aide-au-livre-disque-et-autoproduction-phonographique-jeune-public/consultation',ARRAY['autoproduction','production phonographique'],ARRAY['album','ep','single','spectacle'],ARRAY['porteur de projet'],'2026-04-30'::date,'Dépôts 2026 : du 30 mars au 30 avril. Cycle clos ; conserver pour veille du prochain cycle.',4000::numeric,'Montant 4 000 €. Les critères détaillés varient selon livre-disque ou production phonographique et doivent être vérifiés sur les documents officiels liés à la fiche.','verified',now()),
('SACEM','Aides aux tournées et showcases à l’international – Musiques actuelles et jazz','Soutient le développement de carrière à l’export et les producteurs de spectacles prenant le risque de produire hors de France.','https://aide-aux-projets.sacem.fr/nos-programmes-aide/aides-aux-tournees-et-showcases-linternational-musiques-actuelles-et-jazz/consultation',ARRAY['tournée','export','showcase'],ARRAY['tournee','spectacle'],ARRAY['producteur de spectacles'],NULL::date,'Calendrier à confirmer sur la fiche officielle avant dépôt.',7000::numeric,'Producteur de spectacles ; créateurs en développement à l’export ; tournée d’au moins 5 dates sur 2 mois. Aide limitée à 30 % du budget artistique et des déplacements, jusqu’à 7 000 € pour les tournées et 5 000 € pour les concerts uniques/showcases.','to_verify',NULL::timestamptz),
('SPPF','Aide à la création','Programme d’aide destiné aux producteurs indépendants ; la SPPF distingue notamment création/production, promotion/diffusion et showcase.','https://www.sppf.com/producteur/',ARRAY['création','production'],ARRAY['album','ep','single','clip'],ARRAY['producteur indépendant'],'2026-10-07'::date,'Prochaine commission indiquée : 4 novembre 2026 ; date limite de dépôt : 7 octobre 2026.',NULL::numeric,'Les conditions détaillées d’éligibilité doivent être vérifiées dans l’espace et les règles SPPF avant toute conclusion d’éligibilité.','verified',now())
) as v(provider_name,name,description,official_url,funding_types,project_types,applicant_types,deadline_date,deadline_text,max_amount_eur,eligibility_notes,verification_status,verified_at)
where not exists (select 1 from public.funding_programs p where p.official_url=v.official_url);
