-- Official-source seeds verified 2026-09-21. No invented fixed deadlines.
insert into public.funding_programs
(provider_name,name,description,official_url,funding_types,project_types,applicant_types,deadline_date,deadline_text,max_amount_eur,eligibility_notes,verification_status,verified_at)
select * from (values
('ADAMI','Adami 365 – Aide au projet musical global','Aide directe aux artistes-producteurs associés Adami pour un projet musical global sur 12 mois avec au moins trois volets.','https://www.adami.fr/que-fait-ladami-pour-moi/cherche-financement-projet-artistique/projet-musical-global/',ARRAY['enregistrement','spectacle','promotion','audiovisuel'],ARRAY['album','ep','single','clip','tournee','spectacle'],ARRAY['artiste-interprète associé Adami','structure contrôlée par artiste'],NULL::date,'Commission musique environ toutes les 6 semaines, hors juillet-août. Pas de date fixe publiée sur la fiche.',NULL::numeric,'Artiste principal associé Adami gérant directement sa carrière ; structure contrôlée par l’artiste, productrice et propriétaire majoritaire des masters ; enregistrement obligatoire + au moins deux autres volets. Les prises ne doivent pas être terminées lors de la commission.','verified',now()),
('ADAMI','Aide pour un spectacle de musique','Soutient l’emploi des artistes-interprètes pour la création ou la diffusion d’un spectacle musical.','https://www.adami.fr/que-fait-ladami-pour-moi/cherche-financement-projet-artistique/aide-spectacle-musique/',ARRAY['spectacle vivant','emploi artistique','diffusion'],ARRAY['tournee','spectacle'],ARRAY['association','SARL','EURL','structure privée avec personnalité morale'],NULL::date,'Dépôt au plus tôt 4 mois avant la première représentation et au plus tard le jour de la toute première représentation.',20000::numeric,'Structure privée avec personnalité morale, employeur des artistes et licence entrepreneur de spectacles. Aide = 40 % des salaires bruts éligibles selon plafonds ; au moins 3 artistes-interprètes salariés par représentation et conditions de nombre de dates selon esthétique.','verified',now()),
('ADAMI','Aide première partie musique','Soutient l’emploi des artistes-interprètes programmés en première partie de concert.','https://www.adami.fr/que-fait-ladami-pour-moi/cherche-financement-projet-artistique/aide-premiere-partie-musique/',ARRAY['spectacle vivant','première partie','emploi artistique'],ARRAY['tournee','spectacle'],ARRAY['association','SARL','EURL','structure privée avec personnalité morale'],NULL::date,'Calendrier lié aux représentations ; vérifier les modalités officielles avant dépôt.',6000::numeric,'Structure privée avec personnalité morale employant les artistes, concerts organisés dans le cadre d’une cession avec un tiers et licence entrepreneur de spectacles. Le programme général Adami annonce 70 % des salaires bruts + forfait de 250 € par représentation, plafond 6 000 €.','verified',now()),
('SPEDIDAM','Diffusion du spectacle vivant – Aide au spectacle musical','Aide à la création/diffusion ou à la diffusion du spectacle vivant musical, portant sur le coût total employeur des artistes-interprètes directement employés.','https://www.spedidam.fr/aides-aux-projets/nos-programmes/aide-au-spectacle-musical/',ARRAY['spectacle vivant','diffusion','emploi artistique'],ARRAY['tournee','spectacle'],ARRAY['structure employeuse'],NULL::date,'Les dates du projet, répétitions incluses, doivent être postérieures au dernier jour de la commission d’attribution.',NULL::numeric,'Au moins 6 représentations sur 5 jours minimum ; pour les ensembles d’au moins 8 artistes présents sur scène sur toutes les dates, 4 jours de représentations sont requis. Maximum 10 répétitions. Vérifier l’ensemble des conditions officielles avant dépôt.','verified',now())
) as v(provider_name,name,description,official_url,funding_types,project_types,applicant_types,deadline_date,deadline_text,max_amount_eur,eligibility_notes,verification_status,verified_at)
where not exists (select 1 from public.funding_programs p where p.official_url=v.official_url);
