-- Intentionally no-op.
-- Audit showed that funding workflow transitions deliberately preserve historical
-- submitted_at, decision_at and awarded_amount_eur values. A constraint tying those
-- fields to the current status would reject valid historical records after a status
-- transition (for example awarded -> withdrawn).
--
-- Existing migrations 0048, 0054, 0058 and 0059 already enforce the real invariants:
-- non-negative/coherent amounts, required milestones for submitted/decision states,
-- non-future business dates, and preservation of awarded/post-award history.
