import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, Music2 } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { createWork, deleteWork } from "./actions";
const labels:Record<string,string>={draft:"Brouillon",ready:"Prête",released:"Sortie",to_do:"À déclarer",declared:"Déclarée",not_applicable:"Non concernée"};
export default async function WorksPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}) {
 const params=await searchParams; const s=await createClient(); const {data:{user}}=await s.auth.getUser(); if(!user) redirect("/login");
 const {data:access}=await s.from("user_artist_access").select("artist_id").eq("user_id",user.id).limit(1).maybeSingle(); const artistId=access?.artist_id;
 const works=artistId?(await s.from("works").select("id,title,work_type,status,sacem_status,release_date,notes").eq("artist_id",artistId).order("created_at",{ascending:false})).data??[]:[];
 const toDeclare=works.filter((w:any)=>w.sacem_status==="to_do").length;
 return <main className="mx-auto min-h-screen max-w-md bg-white px-5 pb-28 pt-7">
 <Link href="/" className="inline-flex items-center gap-2 text-sm text-neutral-600"><ArrowLeft size={17}/>Cockpit</Link>
 <div className="mt-6 flex items-center gap-3"><div className="rounded-xl bg-neutral-100 p-3"><Music2/></div><div><p className="text-sm font-semibold text-neutral-500">ArtistPilot</p><h1 className="text-2xl font-bold">Œuvres & droits</h1></div></div>
 <p className="mt-3 text-sm text-neutral-600">Suis tes œuvres, leur sortie et leur déclaration SACEM.</p>
 {params.error&&<p className="mt-4 rounded-xl bg-neutral-100 p-3 text-sm font-medium">Impossible d’enregistrer. Vérifie les informations.</p>}
 {params.success&&<p className="mt-4 rounded-xl bg-neutral-100 p-3 text-sm font-medium">Répertoire mis à jour.</p>}
 <section className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-neutral-950 p-4 text-white"><p className="text-xs text-neutral-400">Œuvres suivies</p><p className="mt-1 text-xl font-bold">{works.length}</p></div><div className="rounded-2xl border p-4"><p className="text-xs text-neutral-500">SACEM</p><p className="mt-1 text-xl font-bold">{toDeclare}</p><p className="text-xs text-neutral-500">à déclarer</p></div></section>
 <section className="mt-7"><h2 className="font-semibold">Répertoire</h2><div className="mt-3 space-y-2">{works.length===0?<p className="rounded-2xl border border-dashed p-5 text-sm text-neutral-500">Aucune œuvre enregistrée.</p>:works.map((w:any)=><div key={w.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{w.title}</p><p className="mt-1 text-xs text-neutral-500">{labels[w.status]??w.status}{w.release_date?" · sortie "+w.release_date:""}</p></div><span className="rounded-full bg-neutral-100 px-2 py-1 text-[11px] font-semibold">{labels[w.sacem_status]??w.sacem_status}</span></div>{w.notes&&<p className="mt-2 text-sm text-neutral-600">{w.notes}</p>}<form action={deleteWork} className="mt-3"><input type="hidden" name="id" value={w.id}/><button className="text-xs font-semibold text-red-700">Supprimer</button></form></div>)}</div></section>
 <section className="mt-8 rounded-3xl border p-5"><h2 className="font-semibold">Ajouter une œuvre</h2><form action={createWork} className="mt-4 space-y-3"><input name="title" required maxLength={180} placeholder="Titre de l’œuvre" className="h-11 w-full rounded-xl border px-3"/><div className="grid grid-cols-2 gap-2"><select name="work_type" className="h-11 rounded-xl border bg-white px-2"><option value="song">Chanson</option><option value="composition">Composition</option><option value="recording">Enregistrement</option><option value="other">Autre</option></select><select name="status" className="h-11 rounded-xl border bg-white px-2"><option value="draft">Brouillon</option><option value="ready">Prête</option><option value="released">Sortie</option></select></div><select name="sacem_status" className="h-11 w-full rounded-xl border bg-white px-2"><option value="to_do">SACEM · à déclarer</option><option value="declared">SACEM · déclarée</option><option value="not_applicable">SACEM · non concernée</option></select><input name="release_date" type="date" className="h-11 w-full rounded-xl border px-3"/><textarea name="notes" maxLength={1000} placeholder="Notes (facultatif)" className="min-h-20 w-full rounded-xl border p-3"/><button className="h-11 w-full rounded-xl bg-black font-semibold text-white">Enregistrer l’œuvre</button></form></section>
 </main>;
}